branches:
  only:
    - win-build

image:
  - Visual Studio 2017

environment:
  - VCPKG_DEFAULT_TRIPLET: x64-windows

init:
  # Uncomment to enable RDP login at init time, this will not block job execution.
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - vcpkg install boost-assign boost-thread boost-program-options boost-filesystem boost-system boost-regex
  # cgal double-conversion eigen3 fontconfig freetype glew glib harfbuzz libxml2 libzip mpfr opencsg qscintilla qt5-base qt5-multimedia qt5-gamepad

cache:
  - c:\tools\vcpkg\installed\

install:
  - ps: Get-Date -UFormat '### %Y-%m-%d %T install started'

build_script:
  - ps: Get-Date -UFormat '### %Y-%m-%d %T build started'

artifacts:
  - path: 'tests\Testing\Temporary\*_report.html'

# Uncomment RDP login at job end with specical blocking flag to prevent the worker from exitting. Continue by deleting lock file on desktop.
# Alternatively if RDP is already enabled earlier, just adding "pause" will block the worker till timeout (60 minutes).
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # - pause
